### ISSUE TITLE
不知道怎么使用

### ISSUE THREAD

**Issue by ssr123456789** [commiyou/qqhelper#1]
能出个教程吗

**Comment by commiyou** [comment]
我目前是使用tasker，profiles-event- intent received，在action一栏填上 com.cooltol.qqhelper.QQ_MSG_SENT 确认
在action里 填上想做的就行了 比如 flash %senduin to %frienduin, msg %msg @%time

**Comment by aabababb** [comment]
同问，是用来定时发QQ消息的？

**Comment by commiyou** [comment]
应用场景是在你跟好友聊天时，把聊天的文本内容给广播出去。
可以用来记录与好友的聊天记录；或者结合tasker设置定时器，提醒每隔多长时间要发送一次消息。
另外qq最新版8.4.10不可用，我刚升级测试。但是8.4.1 以及8.3.x是可用的

**Comment by commiyou** [comment]
最新版8.4.10 兼容了
